#version: '3.8'
services:
    web:
        build: ./docker/php-apache
        volumes:
            - "./src:/usr/src"
        ports:
            - "8080:8080"
        depends_on:
            - db
    db:
        image: mysql:8
        volumes:
            - ./docker/db/data:/var/lib/mysql
            - ./docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=products
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
            - TZ=Asia/Tokyo
        ports:
            - "3306:3306"